### ISSUE TITLE
How should delegates be handled?

### ISSUE THREAD

**Issue by indragiek** [indragiek/ReactiveBLE#1]
The Core Bluetooth API is pretty delegate heavy. Some examples:
- When you call `-scanForPeripheralsWithServices:options:`, the caller is notified of discovered peripherals using the delegate method `-centralManager:didDiscoverPeripheral:advertisementData:RSSI:`
- When you call `-connectToPeripheral:options`, a successful connection results in the delegate method `-centralManager:didConnectPeripheral:` being called.

The best approach I can think of for using this with RAC without imposing restrictions on framework consumers is to implement a proxy object that receives the delegate calls (which can be bridged to the reactive world using `-rac_signalForSelector:`) and then forwards them on to the "normal" delegate if they are implemented. 

If anyone can think of a better solution I'd love to hear it. /cc @kastiglione

**Comment by indragiek** [comment]
Well, looks like RAC has the `RACDelegateProxy` class for handling exactly this. But it's not exposed publicly. Issue: https://github.com/ReactiveCocoa/ReactiveCocoa/issues/1134

**Comment by kastiglione** [comment]
Quick question, are these _pure_ delegates in that they don't provide any data, like `dataSource` delegates?

**Comment by indragiek** [comment]
Correct, they're purely for the purpose of asynchronously delivering results from calls to various methods on CBCentralManager.

**Comment by kastiglione** [comment]
It is possible to get by without `RACDelegateProxy`, I've been in this same situation with `CLLocationManager` and how I handled it was to require the API consumer assign a valid delegate, which was as simple as making the VC or the VM adopt the necessary protocol and assigning `self` as the delegate, even if it didn't implement any methods (i.e. I used only `-rac_signalForSelector:`, never implementing a delegate method directly).

Much of the job of "proxying" is actually taken care of by `-rac_signalForSelector:`. It's true that `RACDelegateProxy` does provide a couple nice extras, but what we're talking about is at least _doable_ without it.

**Comment by Coneko** [comment]
I'd just wrap the whole API in a new class and not bother with interoperability with non-RAC code, otherwise you end up having a very legacy styled API.

Take for example `-scanForPeripheralsWithServices:options:`, `-stopScan` and `-centralManager:didDiscoverPeripheral:advertisementData:RSSI:`;

A `+ (RACSignal *)scanForPeripheralsWithServices:option:` method could be implemented like this:
- On signal subscription, call `-scanForPeripheralsWithServices:options:`.
- On signal disposal, call `-stopScan`.
- On `-centralManager:didDiscoverPeripheral:advertisementData:RSSI:`, send a tuple of the values to the subscriber.

There's no need to expose a way of plugging in a delegate or to interact with the underlying `CBCentralManager` object to the user.

**Comment by kastiglione** [comment]
Notwithstanding @Coneko's good approach, here's how I handled it for `CLLocationManager`, which seems to have some parallels to `CBCentralManager`.

https://github.com/ReactiveCocoa/AnyWall/blob/e67ae31148f8da8c28a1112cf0af9d6aaef8c598/AnyWall/CLLocationManager%2BRACSignalSupport.m

In that case, the caller would look like:

``` objc
CLLocationManager *locationManager = [[CLLocationManager alloc] init];
locationManager.delegate = selfOrSomeAdopterOfCLLocationManagerDelegate;
[locationManager.rac_activeLocationUpdatesSignal subscribeNext:^(CLLocation *x) {
    // stalk user
}];
```

When I wrote that, I liked that it made use of the "normal" Apple supplied classes. But that's of course subjective.

**Comment by indragiek** [comment]
Considering both approaches, I think @Coneko's method is more suitable because the whole idea of allowing the consumer to control the delegate while also hooking into it from RAC seems like a leaky abstraction.

e.g. If I were to create an RAC abstraction around `CBCentralManager -retrieveConnectedPeripheralsWithServices:` (with the results being delivered using the `-centralManager:didRetrieveConnectedPeripherals:` delegate method), the delegate object assigned by the consumer would also receive that delegate method call in addition to the values being sent by the signal, which seems like it would be of no practical benefit.

Does that make any sense or am I misunderstanding how `-rac_signalForSelector:` works?

**Comment by kastiglione** [comment]
> the delegate object assigned by the consumer would also receive that delegate method call in addition to the values being sent by the signal, which seems like it would be of no practical benefit.

The "practical" benefit of this could be when porting existing code, or for giving an escape hatch. These would be more valuable when converting an existing codebase, and/or those who lack confidence in going full RAC.

Go with a clean slate, let the RAC API dictate, not the Apple API.

**Comment by indragiek** [comment]
:+1: Thanks guys.
