### ISSUE TITLE
Peripheral is being disconnected on signal completion.

### ISSUE THREAD

**Issue by lubiluk** [indragiek/ReactiveBLE#14]
In `RBTCentralManager.m` in method `connectPeripheral:options:` a following disposable is being returned:

``` objective-c
return [RACDisposable disposableWithBlock:^{
            [connectedDisposable dispose];
            [failedDisposable dispose];
            [self.CBScheduler schedule:^{
                [self.manager cancelPeripheralConnection:peripheral];
            }];
        }];
```

This means that upon completion of the signal the peripheral will be automatically disconnected. Is that really something that we want? How is one supposed to interact with the peripheral? 
The signal sends our connected peripheral and completes afterwards which means that the peripheral is immediately being disconnected. 
Or am I missing something here?

**Comment by indragiek** [comment]
In the implementation of `-connectPeripheral:options:`, you'll notice that the signal never completes on its own. A subscription to the signal represents a connection to the peripheral. The connection is only disconnected when you manually dispose of the disposable for your subscription. That means you should keep the disposable around for as long as you want the connection to be active and dispose of it when you're done with the connection.

**Comment by lubiluk** [comment]
:sweat_smile: Right. Thanks.

**Comment by lubiluk** [comment]
Well, I kind of still think that it makes it harder to work with the connected peripheral. Sometimes you need to keep that peripheral around long after the signal finishes.
I would rather have another method for disconnecting (actually that's what I have).
Another point is that you never check if the peripheral was disconnected properly. Disconnecting involves delegate methods so I think it's a good candidate to make it a separate signal from it.

**Comment by indragiek** [comment]
The peripheral will be kept around as long as you don't dispose of the disposable that was returned from the subscription. You have a point that the disconnection status isn't checked properly, though. If you can open a separate issue to track that I can look into it.
