### ISSUE TITLE
API for scanning peripherals

### ISSUE THREAD

**Issue by indragiek** [indragiek/ReactiveBLE#2]
`CBCentralManager` has the method `-scanForPeripheralsWithServices:options:` to initiate a scan of peripherals. When peripherals are discovered, the `-centralManager:didDiscoverPeripheral:advertisementData:RSSI:` delegate method is called. Peripheral scanning continues until `-stopScan` is called. 

The tricky part is that a subsequent call to `-scanForPeripheralsWithServices:options:` while a scan is already running replaces the scan parameters with the new ones passed into the method. So anyone who previously subscribed to a signal returned from [`-rbt_scanForPeripheralsWithServices:options`](https://github.com/indragiek/ReactiveBLE/blob/master/ReactiveBLE/CBCentralManager%2BRBTAdditions.m#L18) would now be receiving results for the wrong scan parameters. 

What's the typical RAC way of handling this situation? Have the old signal somehow stop sending values once a new signal is created with different parameters?

**Comment by kastiglione** [comment]
Could the RAC API be immutable by preventing subsequent calls to `-scanForPeripheralsWithServices:options:`? That way signals stay valid until it is disposed. Or put another way, if the the consumer wants to call effectively `-scanForPeripheralsWithServices:options:` with a second set of options, would it be possible to force them to create a new "`RACBluetoothScanner`" object that internally creates a new `CBCentralManager` via `-initWithDelegate:queue:options:`? Can two instances of `CBCentralManager` manage their own independent peripheral scanners?

**Comment by indragiek** [comment]
I'm not entirely sure how an API like that would look like. If I'm wrapping the CB API in another class that exposes an RAC-based interface, the methods on that interface would all have to operate on a single `CBCentralManager`. The only way I can imagine that is if you were splitting the scanning functionality alone into a separate object ("`RACBluetoothScanner`") and exposing the rest of the API elsewhere, since all the other API is only applicable to a particular instance of `CBCentralManager` 

(You can't scan for peripherals on one central and then interact with them from another, the `CBCentralManager` is the root object in a hierarchy of other objects like `CBPeripheral` that are tied to the parent manager).

**Comment by indragiek** [comment]
Implemented in #5.
